spring:
  application:
    name: GatewaySvc
  cloud:
    gateway:
      routes:
        - id: admin-api
          uri: http://localhost:8081
          predicates:
            - Path=/admin/**
        - id: auth-api
          uri: http://localhost:8082
          predicates:
            - Path=/auth/**
        - id: product-api
          uri: http://localhost:8083
          predicates:
            - Path=/products/**
        - id: cart-api
          uri: http://localhost:8084
          predicates:
            - Path=/carts/**
        - id: order-api
          uri: http://localhost:8084
          predicates:
            - Path=/orders/**
        - id: inventory-api
          uri: http://localhost:8085
          predicates:
            - Path=/inventory/**
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
