---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-svc-scaler
  namespace: service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway-svc-pod
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: auth-svc-scaler
  namespace: service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: auth-svc-pod
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: product-svc-scaler
  namespace: service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-svc-pod
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: order-svc-scaler
  namespace: service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-svc-pod
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: inventory-svc-scaler
  namespace: service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inventory-svc-pod
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: web-app-scaler
  namespace: ui
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-app-pod
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
