---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  clusterIP: None
  ports:
    - port: 9200
      name: elasticsearch
    - port: 9114
      name: prometheus
  selector:
    app: elasticsearch
---
apiVersion: v1
kind: Pod
metadata:
  name: logging-pods-elasticsearch
  labels:
    app: elasticsearch
spec:
  initContainers:
    - name: fix-volume-permission
      image: elasticsearch:7.13.2
      command: ['/bin/bash', '-c', 'chown -R 1000:1000 /usr/share/elasticsearch/data']
      securityContext:
        privileged: true
      volumeMounts:
        - name: elasticsearch-storage
          mountPath: /usr/share/elasticsearch/data
  containers:
    - name: prometheus-es-exporter
      image: prometheuscommunity/elasticsearch-exporter
      ports:
        - protocol: TCP
          containerPort: 9114
      args: ["--es.uri=http://elasticsearch:9200"]
    - name: elasticsearch-1
      image: elasticsearch:7.13.2
      imagePullPolicy: Always
      ports:
        - protocol: TCP
          containerPort: 9200
      volumeMounts:
        - mountPath: "/usr/share/elasticsearch/data"
          name: elasticsearch-storage
#      readinessProbe:
#        exec:
#           command:
#           - /bin/bash
#           - -c
#           - /check-readiness.sh
#        initialDelaySeconds: 10
#        periodSeconds: 5
#        successThreshold: 1
      env:
        - name: discovery.type
          value: "single-node"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        - name: xpack.security.enabled
          value: "false"
  volumes:
    - name: elasticsearch-storage
      persistentVolumeClaim:
        claimName: local-disk-elasticsearch-claim

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-disk-elasticsearch-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
      nodePort: 32101
  selector:
    app: kibana
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: logging-pods-kibana
  labels:
    app: kibana
spec:
  containers:
    - name: kibana-1
      image: kibana:7.13.2
      imagePullPolicy: Always
      ports:
        - protocol: TCP
          containerPort: 5601
      env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch:9200"
