---
apiVersion: v1
kind: Service
metadata:
  name: gateway-svc
  labels:
    app: gateway-svc
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: gateway-svc-pods
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-pods-gateway-svc
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gateway-svc-pods
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 25%
       maxSurge: 1
  template:
    metadata:
      labels:
        app: gateway-svc-pods
    spec:
      containers:
      - name: gateway-svc-cont
        image: IMAGE_REGISTRY_PATH/services:REVISION_ID
        args: ["gateway"]
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: log-data
            mountPath: /var/log/oms
        envFrom:
          - configMapRef:
              name: service-config
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 2
      volumes:
        - name: log-data
          emptyDir: {}
      topologySpreadConstraints:                                                                                                                     
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: gateway-svc-pods
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-svc-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway-svc-pods
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
