---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  ports:
    - protocol: TCP
      port: 5601
      targetPort: 5601
      nodePort: 32101
  selector:
    app: kibana
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  name: kibana-1
  labels:
    app: kibana
spec:
  containers:
    - name: kibana-1
      image: kibana:7.13.2
      imagePullPolicy: Always
      ports:
        - protocol: TCP
          containerPort: 5601
      env:
        - name: ELASTICSEARCH_HOSTS
          value: "http://elasticsearch:9200"
