---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
  labels:
    app: order-svc
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: order-svc-pods
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-pods-order-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-svc-pods
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxUnavailable: 25%
       maxSurge: 1
  template:
    metadata:
      labels:
        app: order-svc-pods
    spec:
      initContainers:
      - name: wait-for-postgres
        image: postgres
        command: [ '/bin/bash','-c', 'until pg_isready -h postgres; do echo waiting for postgres; sleep 2; done;' ]
      - name: wait-for-cassandra
        image: cassandra
        command: [ '/bin/bash','-c', 'until echo exit | cqlsh cassandra; do echo waiting for cassandra; sleep 5; done;' ]
      containers:
      - name: order-svc-cont
        image: IMAGE_REGISTRY_PATH/services:REVISION_ID
        args: ["order"]
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: log-data
            mountPath: /var/log/oms
        envFrom:
          - configMapRef:
              name: service-config
        env:
          - name: database.type
            value: SQL
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: secret-config
                key: postgres.user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret-config
                key: postgres.password
        livenessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 180
        readinessProbe:
          httpGet:
            path: /status
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 2
      volumes:
        - name: log-data
          emptyDir: {}
      topologySpreadConstraints:                                                                                                                     
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: order-svc-pods
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: order-svc-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: order-svc-pods
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 70
