---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  clusterIP: None
  ports:
    - port: 5672
      name: default
  selector:
    app: rabbitmq
---
apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq-1
  labels:
    app: rabbitmq
spec:
  containers:
    - name: rabbitmq-1
      image: IMAGE_REGISTRY_PATH/rabbitmq:REVISION_ID
      imagePullPolicy: Always
      ports:
        - protocol: TCP
          containerPort: 5672
      volumeMounts:
        - mountPath: "/var/lib/rabbitmq"
          name: rabbitmq-storage
      readinessProbe: # probe to know when RMQ is ready to accept traffic
        exec:
          command: ["rabbitmq-diagnostics", "ping"]
        initialDelaySeconds: 20
        periodSeconds: 60
        timeoutSeconds: 10	
  volumes:
    - name: rabbitmq-storage
      persistentVolumeClaim:
        claimName: local-disk-rabbitmq-claim
