---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  clusterIP: None
  ports:
    - port: 6379
      name: default
  selector:
    app: redis
---
apiVersion: v1
kind: Pod
metadata:
  name: redis-1
  labels:
    app: redis
spec:
  containers:
    - name: redis-1
      image: IMAGE_REGISTRY_PATH/redis:REVISION_ID
      imagePullPolicy: Always
      ports:
        - protocol: TCP
          containerPort: 6379
      readinessProbe:
        exec:
          command:
          - redis-cli
          - ping
        initialDelaySeconds: 5	
